### ISSUE TITLE
Does not show correct color

### ISSUE THREAD

**Issue by HominisNocturna** [Duckers/Fuse.MaterialDesign#3]
Hi, I'm new on fuse and just downloaded this example and builded it on Android , in local and Android preview shows the correct colors, but when I compile the APK and install it on my phone it doesnt show any color everything its black and white, can you help me?

**Comment by mvondoyannick** [comment]
Hi. android preview show correctly, but when i compile and install APK, some component like Material.ActionButton have a strange apearence, no color, just the icon is visibl. need help. these material component are very awesome.

thanks

**Comment by Duckers** [comment]
Hi! This is due to a bug in Fuse, not a problem in the material design package. Awaiting fix

**Comment by Duckers** [comment]
This is now fixed internally at Fuse, fix will roll out in Fuse 0.31.1 and later

**Comment by Duckers** [comment]
The latest version of Fuse now includes this fix: https://www.fusetools.com/downloads
