### ISSUE TITLE
ux:Ref problem in newer Fuse versions

### ISSUE THREAD

**Issue by eksperts** [Duckers/Fuse.MaterialDesign#9]
As described on forums: https://www.fusetools.com/community/forums/bug_reports/materialdrawerpanel_stop_to_work_with_fuse_100

**Comment by Duckers** [comment]
This has nothing to do with `ux:Ref`, its due to a bug in Fuse 1.0.0 that will be fixed in 1.0.1 

https://github.com/fusetools/fuselibs-public/pull/54
